# This file was generated by the {rix} R package v0.12.4 on 2024-11-25
# with following call:
# >rix(r_ver = "8c4dc69b9732f6bbe826b5fbb32184987520ff26",
#  > r_pkgs = c("tidyverse",
#  > "tinytable",
#  > "quarto",
#  > "remotes",
#  > "janitor",
#  > "readxl",
#  > "here",
#  > "gtsummary",
#  > "geomtextpath",
#  > "permutes",
#  > "permuco",
#  > "cowplot",
#  > "foreach",
#  > "ggokabeito"),
#  > system_pkgs = c("quarto",
#  > "git"),
#  > git_pkgs = list(list(package_name = "webgazer",
#  > repo_url = "https://github.com/jgeller112/webgazeR/",
#  > commit = "1fa04e0ac649fc73843a05ed83d5e7c994c801fe")),
#  > ide = "other",
#  > project_path = path_to_project,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision 8c4dc69b9732f6bbe826b5fbb32184987520ff26 for reproducibility purposes
# which will install R as it was as of nixpkgs revision: 8c4dc69b9732f6bbe826b5fbb32184987520ff26.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8c4dc69b9732f6bbe826b5fbb32184987520ff26.tar.gz") {};

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      ggokabeito
      gtsummary
      here
      janitor
      quarto
      readxl
      remotes
      tidyverse
      tinytable;
  };

  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "webgazer";
      src = pkgs.fetchgit {
        url = "https://github.com/jgeller112/webgazeR/";
        rev = "1fa04e0ac649fc73843a05ed83d5e7c994c801fe";
        sha256 = "sha256-EUj4oD5wf9XJf21xYM+sUZPOg3z/IkI1p9Cf7glfM4U=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          tidyverse;
      };
    })
   ];

  system_packages = builtins.attrValues {
    inherit (pkgs)
      git
      glibcLocales
      nix
      quarto
      R;
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages   ];

}
