# This file was generated by the {rix} R package v0.14.3 on 2025-01-12
# with following call:
# >rix(r_ver = "1876aa1c593bf4013adf5991d8f1884217475432",
#  > r_pkgs = c("tidyverse",
#  > "svglite",
#  > "tinytex",
#  > "flextable",
#  > "knitr",
#  > "webshot2",
#  > "webshot",
#  > "networkD3",
#  > "buildmer",
#  > "tinytable",
#  > "quarto",
#  > "remotes",
#  > "janitor",
#  > "readxl",
#  > "here",
#  > "gtsummary",
#  > "geomtextpath",
#  > "permutes",
#  > "permuco",
#  > "cowplot",
#  > "foreach",
#  > "ggokabeito"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "librsvg"),
#  > git_pkgs = list(list(package_name = "webgazer",
#  > repo_url = "https://github.com/jgeller112/webgazeR/",
#  > commit = "c22a3e072cbf2240a718cd28f80b454fbaa3b905")),
#  >      ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses upstream nixpkgs' revision 1876aa1c593bf4013adf5991d8f1884217475432 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/1876aa1c593bf4013adf5991d8f1884217475432.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      buildmer
      cowplot
      flextable
      foreach
      geomtextpath
      ggokabeito
      gtsummary
      here
      janitor
      knitr
      languageserver
      networkD3
      permuco
      permutes
      quarto
      readxl
      remotes
      svglite
      tidyverse
      tinytable
      tinytex
      webshot
      webshot2;
  };
 
    webgazer = (pkgs.rPackages.buildRPackage {
      name = "webgazer";
      src = pkgs.fetchgit {
        url = "https://github.com/jgeller112/webgazeR/";
        rev = "c22a3e072cbf2240a718cd28f80b454fbaa3b905";
        sha256 = "sha256-yasWm0bevj1WwgdPV4YVcQ4Nz6ceJQL+fqMrsOvvHtc=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          tidyverse;
      };
    });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      librsvg
      nix
      pandoc
      quarto
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ webgazer rpkgs  system_packages   ];
  
}
