# This file was generated by the {rix} R package v0.16.0 on 2025-11-26
# with following call:
# >rix(date = "2025-01-14",
#  > r_pkgs = c("svglite",
#  > "tidyverse",
#  > "networkD3",
#  > "formatR",
#  > "flextable",
#  > "webshot",
#  > "webshot2",
#  > "knitr",
#  > "buildmer",
#  > "tinytable",
#  > "quarto",
#  > "remotes",
#  > "janitor",
#  > "readxl",
#  > "here",
#  > "gtsummary",
#  > "geomtextpath",
#  > "permutes",
#  > "permuco",
#  > "cowplot",
#  > "foreach",
#  > "doParallel",
#  > "ggokabeito"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "librsvg",
#  > "typst"),
#  > git_pkgs = list(list(package_name = "webgazer",
#  > repo_url = "https://github.com/jgeller112/webgazeR/",
#  > commit = "023ebdcb8be6eaac103dcdad4c9b29305cd31e36")),
#  >      tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  > "threeparttable",
#  > "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  > "xstring",
#  > "wrapfig",
#  > "tabularray",
#  > "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-01-14.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      buildmer
      cowplot
      doParallel
      flextable
      foreach
      formatR
      geomtextpath
      ggokabeito
      gtsummary
      here
      janitor
      knitr
      languageserver
      networkD3
      permuco
      permutes
      quarto
      readxl
      remotes
      svglite
      tidyverse
      tinytable
      webshot
      webshot2;
  };
 
    webgazer = (pkgs.rPackages.buildRPackage {
      name = "webgazer";
      src = pkgs.fetchgit {
        url = "https://github.com/jgeller112/webgazeR/";
        rev = "023ebdcb8be6eaac103dcdad4c9b29305cd31e36";
        sha256 = "sha256-C6SRlZH0EFC+/hz22cV3Q8pKXBOzheJfBy+/WVbdODo=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          tidyverse
          janitor
          readxl
          ggokabeito
          here
          knitr
          tinytable
          easystats
          zoo;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      librsvg
      nix
      pandoc
      quarto
      R
      typst
      vscode
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ webgazer rpkgs tex  system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
